### ISSUE TITLE
Accept also the country name for the validation

### ISSUE THREAD

**Issue by pedrofs** [Cimpress-MCP/postal-codes-js#35]
I would like to use it as follows:

```
postalCodes.validate('United Status', '12312');
```

Any concerns?

I can work on a PR.

**Comment by ozankaya** [comment]
Assuming you had a typo and want to use "United States", this seems to be error prone. That country is actually called "United States of America". It would be cumbersome to accept multiple versions of how a country is called. Country names change from time to time as well. For instance Former Yugoslavian Republic of Macedonia became North Macedonia recently.

ISO 3166-1 alpha-2 or alpha-3 country codes are the best for this task. Country name to ISO code conversion should be left to the application.
