### ISSUE TITLE
Ireland Validation: Can not load IE.json

### ISSUE THREAD

**Issue by dyouberg** [Cimpress-MCP/postal-codes-js#38]
Ireland
Country Code: "IE"

Throwing Error on validate function:
`return 'Failed to load postal code format "' + countryData.postalCodeFormat + '".';`

```
"IE": {
    "countryName": "Ireland",
    "postalCodeFormat": "IE.json",
    "alpha2": "IE",
    "alpha3": "IRL",
    "numeric3": "372"
},
```

Traced this to the formats-web.js file missing the import of IE.json

**Comment by ozankaya** [comment]
Fixed in v2.2.3
